# Generated by Django 5.0.1 on 2024-01-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='食物名稱')),
                ('price', models.PositiveIntegerField(verbose_name='食物價格')),
            ],
        ),
    ]
